version: "3.9"

services:
  database_agriness: 
    image: postgres
    container_name: db_agriness
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=agriness
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: agriness
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database_agriness
    depends_on:
      - database_agriness

volumes:
  pgdata:
    driver: local
